definitions:
  datatransfer.ErrorResponse:
    properties:
      code:
        type: integer
      error:
        type: string
    type: object
  datatransfer.SumResponse:
    properties:
      total_price:
        type: integer
    type: object
  model.CustomDate:
    properties:
      time.Time:
        type: string
    type: object
  model.Subscription:
    properties:
      end_date:
        $ref: '#/definitions/model.CustomDate'
      id:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        $ref: '#/definitions/model.CustomDate'
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /subscriptions:
    get:
      description: Получить список всех подписок
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Subscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Get all subscriptions
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      description: Создать новую подписку
      parameters:
      - description: Subscription
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Create subscription
      tags:
      - subscriptions
  /subscriptions/{id}:
    delete:
      description: Удалить подписку по её user_id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Delete subscription
      tags:
      - subscriptions
    get:
      description: Получить информацию о подписке по её user_id
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Get subscription
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновить информацию о подписке
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Updated Subscription
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.Subscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Update subscription
      tags:
      - subscriptions
  /subscriptions/sum:
    get:
      description: Подсчёт суммарной стоимости всех подписок за период с фильтрацией
      parameters:
      - description: User ID
        in: query
        name: id
        type: string
      - description: Service Name
        in: query
        name: service_name
        type: string
      - description: Start period (MM-YYYY)
        in: query
        name: from
        required: true
        type: string
      - description: End period (MM-YYYY)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datatransfer.SumResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/datatransfer.ErrorResponse'
      summary: Calculate total subscription cost
      tags:
      - subscriptions
swagger: "2.0"
